name: Tests
on: push
jobs:
  tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ['3.10', '3.9', '3.8', '3.7']
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Python ${{ matrix.python-version }} - ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install nox==2022.*
    - run: pip install poetry==1.*
    - run: nox -p ${{matrix.python}}
